name: build_repository_docker

on:
  workflow_call:
    secrets:
      DOCKERHUB:
        required: true
      PUSH_TOKEN:
        required: true

  workflow_dispatch:

env:
  BASE_IMAGE: ctumrs/ros_jazzy:latest
  VARIANT: unstable
  DOCKERHUB: ${{secrets.DOCKERHUB}}
  PUSH_TOKEN: ${{secrets.PUSH_TOKEN}}

jobs:

  wait-for-ppa:
    runs-on: ubuntu-22.04
    steps:
      - id: run
        run: |
          sleep 300

  build-docker:
    needs: wait-for-ppa
    runs-on: ubuntu-22.04
    timeout-minutes: 360 # 6 hour timeout
    env:
      DOCKERHUB: ${{secrets.DOCKERHUB}}
      PUSH_TOKEN: ${{secrets.PUSH_TOKEN}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Checkout CI scripts
        uses: actions/checkout@v3
        with:
          repository: ctu-mrs/ci_scripts
          ref: ros2
          path: ci_scripts
          token: ${{secrets.PUSH_TOKEN}}
      - id: build
        run: |
          ./ci_scripts/docker/build_repository_image/build.sh ${{env.BASE_IMAGE}} ${{github.event.repository.name}} ${{env.VARIANT}} ./docker
