name: generic_package_build

on:
  workflow_call:
    secrets:
      PUSH_TOKEN:
        required: true

  workflow_dispatch:

jobs:

  build_amd64:
    uses: ctu-mrs/ci_scripts/.github/workflows/generic_package_build_amd64.yml@containerized
    secrets:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}

  build_arm64:
    uses: ctu-mrs/ci_scripts/.github/workflows/generic_package_build_arm64.yml@containerized
    secrets:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
