name: nix_package_build_amd64

on:
  workflow_call:
    secrets:
      CACHIX:
        required: true
      PUSH_TOKEN:
        required: true

  workflow_dispatch:

env:
  CACHIX_AUTH_TOKEN: ${{secrets.CACHIX}}
  PUSH_TOKEN: ${{secrets.PUSH_TOKEN}}

jobs:

  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
          submodules: 'recursive'
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.PUSH_TOKEN }}
      - uses: cachix/cachix-action@v31
        with:
          name: mycache
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
          extraPullNames: ros ctu-mrs
      # - run: nix run nixpkgs#cachix use ros
      # - run: nix run nixpkgs#cachix use ctu-mrs
      - run: nix build
      - run: nix flake check
