name: nix_package_build_amd64

on:
  workflow_call:
    secrets:
      CACHIX:
        required: true
      PUSH_TOKEN:
        required: true

  workflow_dispatch:

env:
  CACHIX_AUTH_TOKEN: ${{secrets.CACHIX}}
  PUSH_TOKEN: ${{secrets.PUSH_TOKEN}}

jobs:

  build:
    runs-on: ubuntu-24.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          determinate: false

      - uses: DeterminateSystems/magic-nix-cache-action@main
        with:
          use-flakehub: false

      - uses: cachix/cachix-action@v15
        with:
          name: ctu-mrs
          authToken: '${{ secrets.CACHIX }}'
          extraPullNames: ros

      - run: nix build --accept-flake-config
      - run: nix run nixpkgs#cachix -- push ctu-mrs ./result
