name: generic_package_build

on:
  workflow_call:
    secrets:
      PUSH_TOKEN:
        required: true

  workflow_dispatch:

jobs:

  init-artifacts:
    runs-on: ubuntu-22.04
    env:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Checkout CI scripts
        uses: actions/checkout@v3
        with:
          repository: ctu-mrs/ci_scripts
          ref: containerized
          path: ci_scripts
      - id: init_artifacts
        run: |
          mkdir -p /tmp/artifacts
      - id: prime_image
        run: |
          ./ci_scripts/docker/prime_image/prime_image.sh ctumrs/ros_noetic:2025-02-05 noetic_builder_${{ github.RUN_ID }} unstable
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: /tmp/artifacts/
          overwrite: true

  build-job:
    needs: init-artifacts
    runs-on: ubuntu-22.04
    timeout-minutes: 360 # 6 hour timeout
    strategy:
      matrix:
        job: ${{ fromJson(needs.generate-jobs.outputs.packages) }}
      max-parallel: 1 # Run jobs serially
    env:
      TOKEN: ${{ secrets.DOCKERHUB }}
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
    steps:
      - name: Load artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: /tmp/artifacts/
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Checkout CI scripts
        uses: actions/checkout@v3
        with:
          repository: ctu-mrs/ci_scripts
          ref: containerized
          path: ci_scripts
          token: ${{ secrets.PUSH_TOKEN }}
      - id: build
        run: |
          ./ci_scripts/package_build/nonbloom_build/build.sh ctumrs/ros_noetic:2025-02-05 noetic_builder_${{ github.RUN_ID }} /tmp/artifacts $PWD
          ls /tmp/artifacts
      - name: Delete old artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: artifacts
          failOnError: false
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: /tmp/artifacts/
          overwrite: true

  collect-artifacts:
    runs-on: ubuntu-22.04
    needs: build-job
    env:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
    steps:
      - name: Load artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifacts
          path: /tmp/artifacts/
      - id: execute
        run: |
          rm /tmp/artifacts/compiled.txt 2> /dev/null || true
          rm /tmp/artifacts/base_sha.txt 2> /dev/null || true
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'
      - name: Checkout CI scripts
        uses: actions/checkout@v3
        with:
          repository: ctu-mrs/ci_scripts
          ref: containerized
          path: ci_scripts
          token: ${{ secrets.PUSH_TOKEN }}
      - name: Deploy
        run: ./ci_scripts/package_build/push_to_ppa.sh unstable /tmp/artifacts

  delete_builder:
    needs: collect-artifacts
    if: always()
    runs-on: ubuntu-latest
    env:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}
    steps:
      - name: Delete current image
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          packages: '${{ github.event.repository.name }}'
          delete-tags: 'noetic_builder_${{ github.RUN_ID }}'
          token: ${{ secrets.PUSH_TOKEN }}
      - name: Delete old images
        uses: dataaxiom/ghcr-cleanup-action@v1
        with:
          packages: '${{ github.event.repository.name }}'
          older-than: 7 days
          token: ${{ secrets.PUSH_TOKEN }}
