name: ros_package_build

on:
  workflow_call:

  workflow_dispatch:

jobs:

  build_amd64:
    uses: ctu-mrs/ci_scripts/.github/workflows/ros_package_build_and_test_amd64.yml@master

  build_arm64:
    uses: ctu-mrs/ci_scripts/.github/workflows/ros_package_build_and_test_arm64.yml@master
