name: rostest

on:
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-20.04

    env:
      PUSH_TOKEN: ${{ secrets.PUSH_TOKEN }}

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Checkout CI scripts
        uses: actions/checkout@v3
        with:
          repository: ctu-mrs/ci_scripts
          ref: master
          path: .ci_scripts
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Update submodules
        run: |
           sudo pip3 install -U gitman
           [[ -e .gitman.yml || -e .gitman.yaml ]] && gitman install || echo "no gitman modules to install"

      - name: Test
        run: |
          .ci_scripts/rostest/test.sh $GITHUB_WORKSPACE unstable
